# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/parttimenerd/Code/lang/vm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/parttimenerd/Code/lang/vm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parttimenerd/Code/lang/vm/CMakeFiles /home/parttimenerd/Code/lang/vm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parttimenerd/Code/lang/vm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mvm_executable

# Build rule for target.
mvm_executable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mvm_executable
.PHONY : mvm_executable

# fast build rule for target.
mvm_executable/fast:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/build
.PHONY : mvm_executable/fast

#=============================================================================
# Target rules for targets named mvm_library

# Build rule for target.
mvm_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mvm_library
.PHONY : mvm_library

# fast build rule for target.
mvm_library/fast:
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/build
.PHONY : mvm_library/fast

src/env.o: src/env.cpp.o
.PHONY : src/env.o

# target to build an object file
src/env.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/env.cpp.o
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/env.cpp.o
.PHONY : src/env.cpp.o

src/env.i: src/env.cpp.i
.PHONY : src/env.i

# target to preprocess a source file
src/env.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/env.cpp.i
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/env.cpp.i
.PHONY : src/env.cpp.i

src/env.s: src/env.cpp.s
.PHONY : src/env.s

# target to generate assembly for a file
src/env.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/env.cpp.s
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/env.cpp.s
.PHONY : src/env.cpp.s

src/function.o: src/function.cpp.o
.PHONY : src/function.o

# target to build an object file
src/function.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/function.cpp.o
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/function.cpp.o
.PHONY : src/function.cpp.o

src/function.i: src/function.cpp.i
.PHONY : src/function.i

# target to preprocess a source file
src/function.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/function.cpp.i
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/function.cpp.i
.PHONY : src/function.cpp.i

src/function.s: src/function.cpp.s
.PHONY : src/function.s

# target to generate assembly for a file
src/function.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/function.cpp.s
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/function.cpp.s
.PHONY : src/function.cpp.s

src/heap.o: src/heap.cpp.o
.PHONY : src/heap.o

# target to build an object file
src/heap.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/heap.cpp.o
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/heap.cpp.o
.PHONY : src/heap.cpp.o

src/heap.i: src/heap.cpp.i
.PHONY : src/heap.i

# target to preprocess a source file
src/heap.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/heap.cpp.i
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/heap.cpp.i
.PHONY : src/heap.cpp.i

src/heap.s: src/heap.cpp.s
.PHONY : src/heap.s

# target to generate assembly for a file
src/heap.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/heap.cpp.s
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/heap.cpp.s
.PHONY : src/heap.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scope.o: src/scope.cpp.o
.PHONY : src/scope.o

# target to build an object file
src/scope.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/scope.cpp.o
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/scope.cpp.o
.PHONY : src/scope.cpp.o

src/scope.i: src/scope.cpp.i
.PHONY : src/scope.i

# target to preprocess a source file
src/scope.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/scope.cpp.i
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/scope.cpp.i
.PHONY : src/scope.cpp.i

src/scope.s: src/scope.cpp.s
.PHONY : src/scope.s

# target to generate assembly for a file
src/scope.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/scope.cpp.s
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/scope.cpp.s
.PHONY : src/scope.cpp.s

src/stack.o: src/stack.cpp.o
.PHONY : src/stack.o

# target to build an object file
src/stack.cpp.o:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/stack.cpp.o
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/stack.cpp.o
.PHONY : src/stack.cpp.o

src/stack.i: src/stack.cpp.i
.PHONY : src/stack.i

# target to preprocess a source file
src/stack.cpp.i:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/stack.cpp.i
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/stack.cpp.i
.PHONY : src/stack.cpp.i

src/stack.s: src/stack.cpp.s
.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.cpp.s:
	$(MAKE) -f CMakeFiles/mvm_executable.dir/build.make CMakeFiles/mvm_executable.dir/src/stack.cpp.s
	$(MAKE) -f CMakeFiles/mvm_library.dir/build.make CMakeFiles/mvm_library.dir/src/stack.cpp.s
.PHONY : src/stack.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mvm_executable"
	@echo "... mvm_library"
	@echo "... rebuild_cache"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/function.o"
	@echo "... src/function.i"
	@echo "... src/function.s"
	@echo "... src/heap.o"
	@echo "... src/heap.i"
	@echo "... src/heap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scope.o"
	@echo "... src/scope.i"
	@echo "... src/scope.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

